var myData = ["razi", 18, true];
myData.push("king", 7, true);
console.log(myData);
var rgb = [244, 232, 43];
var TimePass = ["razi", "r@gmail.com", 9929292];
console.log(TimePass);
TimePass[0] = "Razi";
console.log(TimePass);
TimePass.push("KingKhan");
console.log(TimePass);
